# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c562977841923bd1c191848dcd446f0eb55ff0b3d50f46a23529ad30bceee9a4602e480f5581298546272837d328268ab55056c1d589fed51afe1064af59eb8f

test:
  secret_key_base: 7a7ba692db17080c7d2b4490dc156079186ba0e3a6a96af0eb4de1a1daf358cb13118b53264fc3b8b8214e1c1de9218a69b95399636996cb2d5328ae367c1ad6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
